gstreamer_camera_node:
  ros__parameters:
    output_topic: /camera/color/image
    compressed_output_topic: /camera/color/image/compressed
    frame_id: front_camera
    multicast_address: 230.1.1.1
    port: 1720
    interface: eth0
    width: 1280
    height: 720
    output_width: 640
    output_height: 360
    decoder: nvidia
    publish_raw: true
    publish_compressed: true
    jitter_latency_ms: 100
    jitter_drop_on_latency: true
    depay_wait_for_keyframe: true
    depay_request_keyframe: true
    h264_config_interval: -1
    disable_dpb: false
    raw_max_fps: 15.0
    compressed_max_fps: 5.0
    jpeg_quality: 90
