video_client_camera_node:
  ros__parameters:
    output_topic: /camera/color/image
    compressed_output_topic: /camera/color/image/compressed
    frame_id: front_camera
    network_interface: eth0
    output_width: 640
    output_height: 360
    publish_raw: true
    publish_compressed: true
    raw_max_fps: 10.0
    compressed_max_fps: 5.0
    request_timeout_s: 1.0
    poll_hz: 30.0
