webrtc_camera_node:
  ros__parameters:
    output_topic: /camera/color/image
    compressed_output_topic: /camera/color/image/compressed
    frame_id: front_camera
    publish_raw: true
    publish_compressed: true
    raw_max_fps: 10.0
    compressed_max_fps: 5.0
    jpeg_quality: 70
    data_channel_id: 2
    enable_audio_transceiver: true
